### PR TITLE
fix: panic when executable not in $PATH

### LINKED ISSUE #205: Go Node segfaults when binary is not found
## 🙂 Expected behavior

Raise a readable error

## 🫠 Actual behavior

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4e0660]

goroutine 34 [running]:
os.(*ProcessState).sys(...)
	/usr/local/go/src/os/exec_posix.go:91
os.(*ProcessState).Sys(...)
	/usr/local/go/src/os/exec.go:170
github.com/cartesi/rollups-node/internal/services.Service.Start({{0x51e257, 0xe}, 0x2afd, {0x52267e, 0x1e}, {0x0, 0x0, 0x0}, {0xc000142000, 0x4c, ...}}, ...)
	/home/gligneul/cartesi/rollups-node/internal/services/service.go:70 +0x220
github.com/cartesi/rollups-node/internal/services.Run.func1()
	/home/gligneul/cartesi/rollups-node/internal/services/service.go:124 +0xb9
created by github.com/cartesi/rollups-node/internal/services.Run in goroutine 1
	/home/gligneul/cartesi/rollups-node/internal/services/service.go:120 +0x305
exit status 2
```

## 🧪 Minimal test case

Start the Go node without one of the binaries in the PATH.

## 🌎 Environment

main

### PR DESCRIPTION
**Pull request by torives**
The Service struct used to evaluate its termination reason to decide if it would return an error or not. This code didn't check for nil pointers and could panic during runtime.

Instead of evaluating the exit code or retrieving the received signal, we changed the design to always exit with an error. It now can be a `context.Canceled` or `exec.ExitError`.

The new code will ignore errors occurring during the exit process after context cancelation. This is by design since this is a rare edge case and the Supervisor is only interested in terminating the process.

Closes #205

### CODE REVIEW

File: internal/services/service_test.go [hunk 1]
```diff
@@ -110,7 +111,24 @@ func (s *ServiceTestSuite) TestServiceReady() {
...
+		Name:            "fake-service",
+		Path:            "wrong-path",
+		HealthcheckPort: s.servicePort,
+	}
+	ctx, cancel := context.WithCancel(context.Background())
+	defer cancel()
+
+	s.NotPanics(func() {
+		err := service.Start(ctx)
+		s.NotNil(err)
```
Comment (gligneul) [inline internal/services/service_test.go:130]: could you check the error?

File: internal/services/service_test.go [hunk 2]
```diff
@@ -110,7 +111,24 @@ func (s *ServiceTestSuite) TestServiceReady() {
 
 	// shutdown
 	cancel()
-	s.Nil(<-result, "service exited for the wrong reason: %v", err)
+	err = <-result
+	s.ErrorIs(err, context.Canceled, "service exited for the wrong reason: %v", err)
+}
+
+// Regression test to catch a panic if the executable is not found in $PATH
```
Comment (renan061) [inline internal/services/service_test.go:118]: Minor of minors, but: we don't need to document this as a "Regression test".
Just `test to catch a panic if the executable is not found in $PATH` is fine.

**Review by renan061 — DISMISSED** [review]

**Review by gligneul — DISMISSED** [review]

**Review by renan061 — APPROVED** [review]

**Review by gligneul — APPROVED** [review]
